name: Build SecureWipe ISO

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget genisoimage syslinux-utils xorriso isolinux
    
    - name: Download Ubuntu ISO
      run: |
        wget -O ubuntu-22.04.5-desktop-amd64.iso \
          https://releases.ubuntu.com/22.04/ubuntu-22.04.5-desktop-amd64.iso
    
    - name: Build SecureWipe ISO
      run: |
        # Extract Ubuntu ISO
        mkdir -p /tmp/iso-mount /tmp/iso-extract
        sudo mount -o loop ubuntu-22.04.5-desktop-amd64.iso /tmp/iso-mount
        sudo cp -rT /tmp/iso-mount /tmp/iso-extract
        sudo umount /tmp/iso-mount
        sudo chmod -R +w /tmp/iso-extract
        
        # Install SecureWipe (exclude large files)
        sudo mkdir -p /tmp/iso-extract/home/securewipe
        sudo cp -r --exclude='*.iso' ./* /tmp/iso-extract/home/securewipe/
        
        # Create autostart
        sudo mkdir -p /tmp/iso-extract/etc/skel/.config/autostart
        sudo cp autostart.desktop /tmp/iso-extract/etc/skel/.config/autostart/
        
        # Build ISO with xorriso (handles large files)
        cd /tmp/iso-extract
        sudo xorriso -as mkisofs -r -V "SecureWipe Live" -J -l \
          -b isolinux/isolinux.bin -c isolinux/boot.cat \
          -no-emul-boot -boot-load-size 4 -boot-info-table \
          -isohybrid-mbr /usr/lib/syslinux/mbr/isohdpfx.bin \
          -o /tmp/securewipe-live.iso .
        
        
        # Move to workspace
        sudo mv /tmp/securewipe-live.iso ./securewipe-live.iso
        sudo chown runner:runner ./securewipe-live.iso
    
    - name: Upload ISO Artifact
      if: "!startsWith(github.ref, 'refs/tags/')"
      uses: actions/upload-artifact@v4
      with:
        name: securewipe-live-iso
        path: securewipe-live.iso
        retention-days: 30
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: securewipe-live.iso
        name: SecureWipe ${{ github.ref_name }}
        body: |
          ## SecureWipe Bootable USB Image
          
          **Download**: `securewipe-live.iso`
          **Size**: ~5GB
          **Base**: Ubuntu 22.04 LTS
          
          ### Usage:
          1. Write ISO to USB drive
          2. Boot from USB
          3. SecureWipe starts automatically
          
          ### Write to USB:
          ```bash
          # Linux
          sudo dd if=securewipe-live.iso of=/dev/sdX bs=4M status=progress
          
          # Windows (PowerShell as Admin)
          dd if=securewipe-live.iso of=\\.\E: bs=4M
          ```
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}